In [ ]:
from torch.utils.data import DataLoader
from dataset import LichessStream, collate
from pathlib import Path
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
batch_size = 75000
num_epochs = 8

learning_rate = 0.0001

# Get the batches of preprocessed data
batches = list(Path("data/split_data").glob("batch_*"))

# Create train/test split
split = int(0.8 * len(batches))

train_stream = LichessStream(batches=batches[:split])
valid_stream = LichessStream(batches=batches[split:])

# train_stream = LichessStream(batches=batches[:1])
# valid_stream = LichessStream(batches=batches[1:2])





In [73]:
train_loader = DataLoader(
    train_stream,
    batch_size=batch_size,
    # num_workers=3,
    collate_fn=collate,
    # prefetch_factor=4,
    pin_memory=True,
    drop_last=True,
)

valid_loader = DataLoader(
    valid_stream,
    batch_size=batch_size,
    num_workers=4,
    collate_fn=collate,
    prefetch_factor=4,
    pin_memory=True,
    drop_last=True,
)

In [70]:
len(train_stream)/75000

1431.6695333333332

In [71]:
700*75000

52500000

In [74]:
for num, (batch_x, batch_y) in enumerate(valid_loader):
    if num % 100 == 0:
        print(num)

0


Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7b6767fab2e0>
Traceback (most recent call last):
  File "/home/msaad/miniconda3/envs/chess/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1663, in __del__
    self._shutdown_workers()
  File "/home/msaad/miniconda3/envs/chess/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1646, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/home/msaad/miniconda3/envs/chess/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process


100


Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7b6767fab2e0>
Traceback (most recent call last):
  File "/home/msaad/miniconda3/envs/chess/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1663, in __del__
    self._shutdown_workers()
  File "/home/msaad/miniconda3/envs/chess/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1646, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/home/msaad/miniconda3/envs/chess/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process


200


Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7b6767fab2e0>
Traceback (most recent call last):
  File "/home/msaad/miniconda3/envs/chess/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1663, in __del__
    self._shutdown_workers()
  File "/home/msaad/miniconda3/envs/chess/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1646, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/home/msaad/miniconda3/envs/chess/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7b6767fab2e0>
Traceback (most recent call last):
  File "/home/msaad/miniconda3/envs/chess/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1663, in __del__
    self._shutdown_workers()
  File "/home/msaad/miniconda3/en

300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700


Exception in thread Thread-99 (_pin_memory_loop):
Traceback (most recent call last):
  File "/home/msaad/miniconda3/envs/chess/lib/python3.12/threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "/home/msaad/miniconda3/envs/chess/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
  File "/home/msaad/miniconda3/envs/chess/lib/python3.12/threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "/home/msaad/miniconda3/envs/chess/lib/python3.12/site-packages/torch/utils/data/_utils/pin_memory.py", line 61, in _pin_memory_loop
    do_one_step()
  File "/home/msaad/miniconda3/envs/chess/lib/python3.12/site-packages/torch/utils/data/_utils/pin_memory.py", line 37, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/msaad/miniconda3/envs/chess/lib/python3.12/multiprocessing/queues.py", line 122, in get
    r

KeyboardInterrupt: 

In [63]:
batch_x.shape

torch.Size([75000, 837])

In [64]:
batch_y

tensor([ 203,  455, 1935,  ...,  108,  597,  886])

In [60]:
batch_x

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [59]:
batch_y.shape

torch.Size([75000])

In [36]:
batches = list(Path("data/split_data").glob("batch_*"))

# Create train/test split
split = int(0.8 * len(batches))

In [37]:
dataset = LichessStream(batches)

In [43]:
batches[4::10]

[PosixPath('data/split_data/batch_123'),
 PosixPath('data/split_data/batch_43'),
 PosixPath('data/split_data/batch_176'),
 PosixPath('data/split_data/batch_122'),
 PosixPath('data/split_data/batch_192'),
 PosixPath('data/split_data/batch_90'),
 PosixPath('data/split_data/batch_164'),
 PosixPath('data/split_data/batch_0'),
 PosixPath('data/split_data/batch_30'),
 PosixPath('data/split_data/batch_147'),
 PosixPath('data/split_data/batch_158'),
 PosixPath('data/split_data/batch_79'),
 PosixPath('data/split_data/batch_17'),
 PosixPath('data/split_data/batch_134'),
 PosixPath('data/split_data/batch_97'),
 PosixPath('data/split_data/batch_69'),
 PosixPath('data/split_data/batch_148'),
 PosixPath('data/split_data/batch_151'),
 PosixPath('data/split_data/batch_180'),
 PosixPath('data/split_data/batch_46')]

In [39]:
for thing in dataset:
    print(thing)
    

data/split_data/batch_109
data/split_data/batch_41
data/split_data/batch_106
data/split_data/batch_70
data/split_data/batch_123
data/split_data/batch_135
data/split_data/batch_1
data/split_data/batch_5
data/split_data/batch_81
data/split_data/batch_169
data/split_data/batch_85
data/split_data/batch_77
data/split_data/batch_38
data/split_data/batch_66
data/split_data/batch_43
data/split_data/batch_131
data/split_data/batch_99
data/split_data/batch_37
data/split_data/batch_11
data/split_data/batch_50
data/split_data/batch_64
data/split_data/batch_60
data/split_data/batch_143
data/split_data/batch_26
data/split_data/batch_176
data/split_data/batch_128
data/split_data/batch_193
data/split_data/batch_12
data/split_data/batch_190
data/split_data/batch_141
data/split_data/batch_78
data/split_data/batch_57
data/split_data/batch_130
data/split_data/batch_100
data/split_data/batch_122
data/split_data/batch_13
data/split_data/batch_18
data/split_data/batch_167
data/split_data/batch_125
data/split

In [19]:
next(dataset._yield_rows_from_batch(batches[0]))

(array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [ ]:
next(dataset)

TypeError: 'LichessStream' object is not an iterator